name: Go - Development Build

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  # Cancels pending runs when a PR gets updated.
  group: ${{ github.head_ref || github.run_id }}-${{ github.actor }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version:
          - 1.22.6
          - 1.23.0

    steps:
      - uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 0
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5.0.2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Display Go version
        run: go version

      - name: Install Go Dependencies
        run: go get ./...

      - name: Execute Go Build
        run: go build -v ./...

      - name: Execute Go Test
        run: go test -v ./...

  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v5.0.2
        with:
          go-version: 1.22.6
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6.1.0
        with:
          version: v1.60.1
          args: --timeout=10m
