name: Go

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.17.13', '1.18.10', '1.19.5' ]

    steps:
      - uses: actions/checkout@v3.3.0
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v3.5.0
        with:
          go-version: ${{ matrix.go-version }}

      - name: Display Go version
        run: go version

      - name: Install dependencies
        run: go get .

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - name: Setup Go
        uses: actions/setup-go@v3.5.0
        with:
          go-version: 1.19.5

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3.3.1
        with:
          version: latest

