name: Go - Release Build

on:
  push:
    tags:
      - "*"

concurrency:
  # Cancels pending runs when a PR gets updated.
  group: ${{ github.head_ref || github.run_id }}-${{ github.actor }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - name: Setup Go
        uses: actions/setup-go@v4.1.0
        with:
          go-version: 1.20.12
      - name: Execute GoReleaser
        uses: goreleaser/goreleaser-action@v5.0.0
        if: startsWith(github.ref, 'refs/tags/')
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
